name: Code Analysis
on: 
  push:
    branches:
      - 'master'
jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A ${{ github.event_name }} event happened, starting codeql job."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with: 
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - run: echo "Job ended."
  bandit:
    runs-on: ubuntu-latest
    steps:
    - run: echo "A ${{ github.event_name }} event happened, starting bandit job."
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.6'
    - run: pip install bandit
    - run: bandit -r $GITHUB_WORKSPACE